$(`<a href="قريآ" target="_blank" style=" font-family:'El Messiri',sans-serif;
  width:107px;
  color:#ff0000;
  text-decoration:none;
  margin-right:5px;
  margin-left:2px;
  text-align:center;
  float:right;
  border-radius:5px;
  border-color:#F2F2F2;
  padding:3px;
  " class="border" ><i class="fa fa-android"></i> التطبيق</a>`).insertBefore('a.fl.fa.fa-ban.btn.ui-corner-all.ui-shadow.ui-btn.ui-btn-inline.umute.borderg');
$(".ae.label.label-primary.fa.fa-gear").text(' ضبط');
$(".ae.fa.label.label-primary.fa-users").text('غرف');
$('.nav-tabs').addClass('fl').css('width','100%');
