$(`<img src="https://6.top4top.net/p_1456pfos81.png" class="fr" style="width:100%;margin-right: 1px;">

<div><marquee direction="right" width="99%" id="asim7" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="2">    شات نـسـيـم  بـغـداد  للجوال السعادة تجمعنا  ●اهلا وسهلا بكم في دردشة نـسـيـم  بـغـداد  ● · لا تدع الدردشة تلهيك عن صلاتك ولا تستخدم الشات في ما لا يرضي الله  </marquee></div>
<div id="asim10"><center><a id="asim33" href="iraqstar1.com" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">التطبيق</a><a id="asim33" href="iraqstar1.com" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">اشتراكات</a>
<div id="asim10"><center><a id="asim33" href="iraqstar1.com" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">نـسـيـم</a><a id="asim33" href="iraqstar1.com" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">بـغـداد</a>
<div id="asim10"><center><a id="asim33" href="iraqstar1.com" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">مدونه</a><a id="asim33" href="iraqstar1.com" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">نسيم</a>
<div id="asim10"><center><a id="asim33" href="iraqstar1.com" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">بغداد</a>
<style>
`).insertBefore('.nav-tabs');
$.getScript("");
$(`<link rel="stylesheet" href="https://raw.githack.com/abbassaad995/test.css/master/neo.css
" item="" str=""><style>label.fl.nosel.label.pnhead {background-color: #267a84;}</style><link rel="stylesheet" href="https://raw.githack.com/abbassaad995/test.css/master/neo1.css" item="" str="">`).insertBefore("body");
$(`<div><marquee direction="right"id="as43"scrollamount="3">اهلا وسهلا بكم في دردشة نسيم بغداد  هنا تحجي وتسولف ويا اصدقائك بنات وشباب وتتعرف على اصدقاء من جميع انحاء العالم عراقيين عرب اكراد اجانب هدفنا التجمع تحت سقف دردشة كلنا العراق  تحشيش ضحك شقه وسوالف حلوه تبدال الخواطر والمشاعر وهمس الكلام بين بنوتات وشباب دردشتنا والتعبير ما بيننا بـ درر الكلام واصايل الرومانسية حيث نبث الحرية في سماء عراقنا الحبيب ووطنا الجميل ونعيش ليالينا مع عشق لمة اهلنا من بنوتة وشاب بعيدا عن الـ بعثرة ومشاكل الحياة وهنا يكون هذا الـ عالم النبلاء ونسيم بغداد- · ● · مع تمنياتنا للجميع بأطيب الاوقات  </marquee><div>`).insertBefore("div#tlogins .lonline.light.break"); $(".hand.nosel.fl.uzr.border").css({ margin: "1px 0", borderRadius: "0px" }), $(".checkbox label").html(`<input id="stealth" type="checkbox" value=""><i class="fa fa-eye-slash" aria-hidden="true"></i>`), $(".nav-tabs").addClass("fl").css("width", "100%"), $("div#tlogins input").attr("maxlength", 12), $("textarea#tbox.fl.corner.tbox.filw").attr("maxlength", 100), $("div#tlogins button.btn.btn-primary").click(function() { var a = setInterval(function() { var b = $(".pmsgc").length; 0 < b ? (clearInterval(a)) : console.log(b) }, 1) }), $(document).ready(function() { $('#asjs, textarea#tbox').on("cut copy paste", function(e) { e.preventDefault(); }); }); $("div#tlogins button.btn.btn-primary").click(function() { setTimeout(function() { refreshonline() }, 0) }), $("div#tlogins button.btn.btn-primary").click(function() { var a = setInterval(function() { var b = $(".pmsgc").length; 0 < b ? ($(``).appendTo("#mic"), clearInterval(a)) : console.log(b) }, 1) }), $("div#tlogins button.btn.btn-primary").click(function() { setTimeout(function() { refreshonline() }, 0) }), setInterval(function() { var b = $("#dpnl"); 0 < b.length && b.remove() }, 0), $(".dpnl").append(` <div id="mic" style="height: 100%;width:100%;" class="break light tab-pane border"><iframe id="asim29" src="https://blog.iraqiichat.com/radio/" frameborder="no"></iframe><a rel="nofollow" title="" href="http://mixlr.com/%D8%B4%D8%A7%D8%AA-%D9%86%D8%B3%D9%8A%D9%85-%D8%A8%D8%BA%D8%AF%D8%A7%D8%AF-%D9%84%D9%84%D8%AC%D9%88%D8%A7%D9%84/" target="_blank" class="fl mini fa fa-microphone  btn btnn-default" style="width: 99%;">الإتصال بالإذاعة</a><a class="fl mini fa fa-bullhorn  btn label-primary">اسم البرنامج</a><input type="asim" name="FirstName" value="mixlr"></div><center><center></div><center></div>`), $("#d0").append(`<label title="اذاعة نسيم بغداد "href="#"onclick="$('.pnhead').text($(this).attr('title'));hl($(this),'primary');setTimeout(function(){$('#mic').scrollTop(0);},0);$('.dpnl').show();"data-toggle="tab" data-target="#mic" class="ae fa label label-primary "><i class="fa fa-volume-up" aria-hidden="true"></i></label>`);$("a.fa.fa-user-plus").text('تسجيل');
